#Sample .travis.yml for R projects

language: r
r:
 - 3.5.1
 - release
 - devel
package: cache
r_build_args: " --no-resave-data"
r_check_args: "--timings"
-os:
  - linux
  - osx
  - windows

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'